---
title: "day11_stripes"
author: "Lyndsay Miles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
```

```{r}
global_temps <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-07-11/global_temps.csv')
nh_temps <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-07-11/nh_temps.csv')
sh_temps <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-07-11/sh_temps.csv')
zonann_temps <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-07-11/zonann_temps.csv')


```

```{r}
#Average spring temperature (March-April-May)
#estimate of global surface temperature change
df <- global_temps %>% 
  select(Year, MAM) 
```

```{r}
#https://stats4sd.org/blog/67
ggplot(data=df,aes(x=Year,y=1,fill=MAM))+
  geom_col()+
  scale_fill_gradient2(low = "#7fbf7b",mid="white",high="#9332a8")+
  labs(fill = "",
       x = "",
       y= "",
       title = "Year-over-Year Change in Global Spring Temperatures, 1880-2023",
       caption = "Author: Lyndsay Miles\nSource: TidyTuesday/NASA GISTEMPV4")+
  theme_minimal()+
  theme(axis.text.y = element_blank(),
        axis.ticks = element_blank())

```


