---
title: "day1_fractions"
author: "Lyndsay Miles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(hrbrthemes)
library(fontawesome)

pkg_themes <- getNamespaceExports("hrbrthemes")
pkg_themes <- sort(pkg_themes[grepl("^theme\\_", pkg_themes)])

glue::glue("- `{pkg_themes}()`")
```
Fractions: MTG cards
```{r}
mtg_cards <- readr::read_csv('data/all_mtg_cards.csv')

mtg_cards <- mtg_cards%>%mutate_if(is.character, as.factor)
```

```{r}
p_frac <- mtg_cards %>% group_by(rarity) %>% summarize(totcnt = n()) 
```

```{r}
df <- mtg_cards %>% 
  #filter(rarity %in% c("Common", "Mythic", "Rare", "Uncommon"))%>%
  drop_na(rarity)%>%
  group_by(rarity) %>% summarize(totcnt = n())%>% 
  mutate(perc = totcnt/sum(totcnt))
```

```{r}
ggplot(df, aes(x = fct_reorder(rarity, desc(perc)), y = perc, fill = rarity)) +
  #geom_segment(aes(x = rarity, xend = rarity, y = 0, yend = perc)) +
  #geom_point(size = 4, pch = 21, bg = 4, col = 1) +
  geom_bar(stat = "identity")+
  scale_y_continuous(labels = scales::percent)+
  labs(x = "", y = "",
       fill = "Rarity",
       title = "Magic the Gathering: The Most Common Card Type Is Rare?",
       subtitle = "30DayChartChallenge, Day 1: Fractions",
       caption = "Data source: Kaggle (Myles O'Neill)")+
  
  #scale_fill_manual(values = c("#c4d3ca", "#b3ceea", "#eb8b82", "#f8e7b9", "#a69f9d", "black")) +
    scale_fill_manual(values = c("black", "#a69f9d", "#eb8b82", "#f8e7b9", "#b3ceea", "#c4d3ca")) +
  coord_flip() +
  theme_minimal()

```

