---
title: "day4_big_small"
author: "Lyndsay Miles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(hrbrthemes)
library(ggplot2)
pkg_themes <- getNamespaceExports("hrbrthemes")
pkg_themes <- sort(pkg_themes[grepl("^theme\\_", pkg_themes)])
library(jpeg)

glue::glue("- `{pkg_themes}()`")
```

```{r}
pokemon_df <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-04-01/pokemon_df.csv')

```

```{r}
#calculate pokemon BMI

pokemon_df <- pokemon_df %>% 
  mutate(bmi = weight/(height^2))
```

```{r}
#colors by type
poke_colors <- pokemon_df %>% 
  select(type_1, color_1) %>%
  distinct(type_1, color_1)

#are some pokemon types bigger? 
df_plot <- pokemon_df %>%
  mutate(type_1 = as_factor(type_1))

df_plot %>% 
  group_by(type_1) %>% 
  summarize(avg_bmi = round(mean(bmi),0)) %>% 
  arrange(avg_bmi) %>% 
  ggplot(aes(x= reorder(type_1, avg_bmi), y=avg_bmi, fill = type_1))+ 
  geom_bar(stat = "identity")+
  geom_text(aes(label = avg_bmi), hjust = 1.2)+
  labs(x = "", y = "Average BMI",
       title = "Pokemon by Type and Size",
       caption = "Author: Lyndsay Miles | Source: TidyTuesday")+
  scale_fill_manual(values = c("#78C850", "#F08030", "#6890F0", "#A8B820",
                               "#A8A878", "#A040A0", "#F8D030", "#E0C068",
                               "#EE99AC", "#C03028", "#F85888", "#B8A038",
                               "#705898", "#98D8D8", "#7038F8", "#705848",
                               "#B8B8D0", "#A890F0"))+
  coord_flip()+
  theme_ipsum_pub()+
  theme(legend.position="none")
  
```





