---
title: "day7_outliers"
author: "Lyndsay Miles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
```
https://www.cia.gov/the-world-factbook/references/guide-to-country-comparisons/
CIA Factbook, Country Comparisons 2014 
```{r}
cia_factbook <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2024/2024-10-22/cia_factbook.csv')

# Mostly clean data provided by the {usdatasets} R package
# (https://cran.r-project.org/package=usdatasets). No cleaning was necessary.

pak::pak("usdatasets")
library(dplyr)
library(usdatasets)
cia_factbook <- usdatasets::cia_factbook_tbl_df |> 
  dplyr::mutate(
    dplyr::across(
      c("area", "internet_users"),
      as.integer
    )
  )
```

```{r}
cia_factbook <- cia_factbook %>% 
  mutate(label_name = case_when(country %in% "Syria" ~ "Syria",
                                country %in% "Lebanon" ~ "Lebanon",
                                country %in% "Afghanistan" ~ "Afghanistan",
                                .default = "" ))
```


```{r}
library(scales)
p1 <- ggplot(data = cia_factbook, aes(x=infant_mortality_rate, y= population_growth_rate, label = label_name))+
  geom_point()+
  geom_text(size = 3, hjust = 0.75, vjust = -0.5)+
  labs(title = "Infant Mortality Outliers",
       x = "Infant mortality rate",
       y = "Population growth rate",
       subtitle = "CIA Factbook Country Comparison, 2014",
       caption = "Author: Lyndsay Miles\nSources: CIA Factbook/TidyTuesday")+
  hrbrthemes::theme_modern_rc()+
  theme(legend.position = "bottom")
p1
```



